import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/components/shared/TopNav";


export const metadata: Metadata = {
  title: "Moo printing",
  description: "Generated by pringing services",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav/>
        {children}
      </body>
    </html>
  );
}
